import { Button } from '../components/ui/button';
import { Download } from 'lucide-react';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';
import { formatDateTime, formatPercentage } from '../utils/format';

const DownloadReportButton = ({ result, slideName = 'Unknown Slide' }) => {
  const generatePDF = () => {
    try {
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(24);
      doc.setTextColor(79, 70, 229);
      doc.text('MicroX AI Analysis Report', 20, 25);
      
      // Slide Info
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`Slide: ${slideName}`, 20, 40);
      doc.text(`Analysis Date: ${formatDateTime(result.timestamp)}`, 20, 50);
      doc.text(`Processing Time: ${result.processingTime.toFixed(2)}s`, 20, 60);
      
      // Diagnosis
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Diagnosis Results', 20, 80);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.text(result.diagnosis, 20, 90);
      doc.text(`Confidence: ${formatPercentage(result.confidence)}`, 20, 100);
      doc.text(`Category: ${result.category}`, 20, 110);
      
      // Regions Table
      autoTable(doc, {
        startY: 130,
        head: [['Region Type', 'Confidence']],
        body: result.regions.map(region => [
          region.type,
          formatPercentage(region.confidence)
        ]),
        theme: 'striped',
        styles: {
          fontSize: 10,
          cellPadding: 5
        }
      });
      
      // Additional Details
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Additional Analysis Details', 20, 190);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const details = [
        `Model Version: ${result.modelVersion}`,
        `Abnormalities Detected: ${result.abnormalitiesDetected}`,
        `Classification: ${result.predictedClassName}`,
        'Analysis includes automated detection and classification'
      ];
      details.forEach((line, index) => {
        doc.text(line, 25, 200 + (index * 10));
      });
      
      // Important Notice
      doc.setFontSize(10);
      doc.setTextColor(234, 88, 12);
      doc.text('⚠ Important Notice:', 20, 250);
      doc.setTextColor(0, 0, 0);
      doc.text([
        'This report is generated by AI for preliminary analysis only.',
        'Final diagnosis should be made by qualified medical professionals.'
      ], 20, 260);
      
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(`Generated by MicroX AI - ${formatDateTime(new Date())}`, 20, 280);
      
      doc.save(`pathology-report-${Date.now()}.pdf`);
    } catch (error) {
      console.error('PDF Generation Error:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  return (
    <Button 
      onClick={generatePDF} 
      className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white"
    >
      <Download size={16} />
      Download Report
    </Button>
  );
};

export default DownloadReportButton;